services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
   
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - BYPASS_WEB_SEARCH_WEB_LOADER=True
      - ENABLE_RAG_HYBRID_SEARCH=True
      - ENABLE_RAG_WEB_SEARCH_SEARCH_RESULT_RERANKING=True
      - RAG_RERANKING_ENGINE=external
      - RAG_RERANKING_MODEL=BAAI/bge-reranker-v2-m3
      - RAG_EXTERNAL_RERANKER_API_KEY=dummy
      - RAG_EXTERNAL_RERANKER_URL=http://infinity:7997/rerank
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&engines=qwant,bing&format=json
      - WEB_SEARCH_RESULT_COUNT=3
      - ENABLE_PERSISTENT_CONFIG=false
    volumes:
      - open-webui_data:/app/backend/data
    restart: unless-stopped
    depends_on:
      - ollama

  searxng:
    image: docker.io/searxng/searxng
    container_name: searxng
    ports:
      - "8081:8080"
    volumes:
      - searxng_data:/etc/searxng:Z
    environment:
      - SEARXNG_HOSTNAME=http://localhost:8081/
      - SEARXNG_LIMITER=false
    restart: unless-stopped
  
  infinity:
    image: michaelf34/infinity:latest
    container_name: infinity
    ports:
      - "7997:7997"
    volumes:
      - infinity_data:/app/.cache:Z
    command: v2 --model-id BAAI/bge-reranker-v2-m3 --device cpu
    restart: unless-stopped

volumes:
  ollama_data:
  open-webui_data:
  searxng_data:
  infinity_data:
